const ERROR_BAD_REQUEST = 400;
const UNAUTHORIZED_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const ERROR_NOT_FOUND = 404;
const ERROR_INTERNAL_SERVER = 500;
const CONFLICT_REQUEST = 409;

module.exports = {
  ERROR_BAD_REQUEST,
  ERROR_NOT_FOUND,
  ERROR_INTERNAL_SERVER,
  CONFLICT_REQUEST,
  UNAUTHORIZED_ERROR,
  FORBIDDEN_ERROR,
};
